# Generated by Django 6.0.5 on 2026-05-21 05:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_date", models.DateTimeField(auto_now_add=True)),
                ("students_analyzed", models.IntegerField()),
                ("records_processed", models.IntegerField()),
                ("stress_alerts_count", models.IntegerField()),
                ("details", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="HMMPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha de predicción")),
                (
                    "hidden_state",
                    models.CharField(
                        choices=[
                            ("motivado", "Motivado"),
                            ("cansado", "Cansado"),
                            ("estresado", "Estresado"),
                            ("desmotivado", "Desmotivado"),
                        ],
                        max_length=20,
                        verbose_name="Estado oculto",
                    ),
                ),
                (
                    "probability",
                    models.FloatField(verbose_name="Probabilidad asociada"),
                ),
                (
                    "is_stressed",
                    models.BooleanField(default=False, verbose_name="Alerta de estrés"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Predicción HMM",
                "verbose_name_plural": "Predicciones HMM",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha del registro")),
                (
                    "study_hours",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Horas de estudio",
                    ),
                ),
                (
                    "tasks_delivered",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tareas entregadas",
                    ),
                ),
                (
                    "attendance",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Asistencia (%)",
                    ),
                ),
                (
                    "sleep_hours",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Horas de sueño",
                    ),
                ),
                (
                    "delivery_delays",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Retrasos en entregas",
                    ),
                ),
                (
                    "academic_activity_time",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tiempo de actividad académica (horas)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro académico",
                "verbose_name_plural": "Registros académicos",
                "ordering": ["-date"],
                "unique_together": {("student", "date")},
            },
        ),
    ]
